name: 3 - platform policy definitions

on:
  # Triggers the workflow on push or pull request events but only for the main branch
 # push:
 #  branches: 
 #     - main 
 #  paths:
 #    - .github/workflows/eslz-platform-policy-definitions.yml
      
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: Azure/cli@v1
      name: 'Lint and Build Bicep'
      with:
        inlineScript: |
          az bicep build --file ./eslz/policy/customPolicyDefinition.bicep
          az bicep build --file ./eslz/policy/customPolicyDiagLaw.bicep
          az bicep build --file ./eslz/policy/customPolicyDiagStgAcct.bicep

  validate: 
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: ${{ secrets.AZURE_ENVIRONMENT }}
          enable-AzPSSession: false
        
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}

    - uses: Azure/cli@v1
      name: 'Run preflight validation'
      with:
        inlineScript: |
            az deployment mg validate \
              --name 'Platform-Policy-Definitions' \
              --location ${{ secrets.AZURE_LOCATION }} \
              --management-group-id ${{ secrets.AZURE_MG_TOP }} \
              --template-file ./eslz/policy/customPolicyDefinition.bicep \
              --parameters location=${{ secrets.AZURE_LOCATION }} \
                           targetMgId=${{ secrets.AZURE_MG_TOP }}
            az deployment mg validate \
              --name 'Platform-Policy-Definitions' \
              --location ${{ secrets.AZURE_LOCATION }} \
              --management-group-id ${{ secrets.AZURE_MG_TOP }} \
              --template-file ./eslz/policy/customPolicyDiagLaw.bicep \
              --parameters location=${{ secrets.AZURE_LOCATION }} \
                           targetMgId=${{ secrets.AZURE_MG_TOP }}
            az deployment mg validate \
              --name 'Platform-Policy-Definitions' \
              --location ${{ secrets.AZURE_LOCATION }} \
              --management-group-id ${{ secrets.AZURE_MG_TOP }} \
              --template-file ./eslz/policy/customPolicyDiagStgAcct.bicep \
              --parameters location=${{ secrets.AZURE_LOCATION }} \
                           targetMgId=${{ secrets.AZURE_MG_TOP }}

  preview:
      runs-on: ubuntu-latest
      needs: [validate]
      steps:
      - uses: actions/checkout@v2
      
      - uses: azure/login@v1
        name: 'Login to Azure'
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         environment: ${{ secrets.AZURE_ENVIRONMENT }}
         enable-AzPSSession: false
        
      - name: 'Set Azure Subscription'
        run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}
                
      - uses: Azure/cli@v1
        name: 'Run what-if'
        with:
          inlineScript: |
            az deployment mg what-if \
              --name 'Platform-Policy-Definitions' \
              --location ${{ secrets.AZURE_LOCATION }} \
              --management-group-id ${{ secrets.AZURE_MG_TOP }} \
              --template-file ./eslz/policy/customPolicyDefinition.bicep \
              --parameters location=${{ secrets.AZURE_LOCATION }} \
                           targetMgId=${{ secrets.AZURE_MG_TOP }}
            az deployment mg what-if \
              --name 'Platform-Policy-Definitions' \
              --location ${{ secrets.AZURE_LOCATION }} \
              --management-group-id ${{ secrets.AZURE_MG_TOP }} \
              --template-file ./eslz/policy/customPolicyDiagLaw.bicep \
              --parameters location=${{ secrets.AZURE_LOCATION }} \
                           targetMgId=${{ secrets.AZURE_MG_TOP }}
            az deployment mg what-if \
              --name 'Platform-Policy-Definitions' \
              --location ${{ secrets.AZURE_LOCATION }} \
              --management-group-id ${{ secrets.AZURE_MG_TOP }} \
              --template-file ./eslz/policy/customPolicyDiagStgAcct.bicep \
              --parameters location=${{ secrets.AZURE_LOCATION }} \
                           targetMgId=${{ secrets.AZURE_MG_TOP }}

  deploy:
    runs-on: ubuntu-latest
    needs: [preview]
    environment: Production
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: ${{ secrets.AZURE_ENVIRONMENT }}
        enable-AzPSSession: false
      
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}
              
    - uses: Azure/cli@v1
      name: 'Deploying Custom Policy Definitions'
      with:
        inlineScript: |
            az deployment mg create \
              --name 'Platform-Policy-Definitions' \
              --location ${{ secrets.AZURE_LOCATION }} \
              --management-group-id ${{ secrets.AZURE_MG_TOP }} \
              --template-file ./eslz/policy/customPolicyDefinition.bicep \
              --parameters location=${{ secrets.AZURE_LOCATION }} \
                           targetMgId=${{ secrets.AZURE_MG_TOP }}
            az deployment mg create \
              --name 'Platform-Policy-Definitions' \
              --location ${{ secrets.AZURE_LOCATION }} \
              --management-group-id ${{ secrets.AZURE_MG_TOP }} \
              --template-file ./eslz/policy/customPolicyDiagLaw.bicep \
              --parameters location=${{ secrets.AZURE_LOCATION }} \
                           targetMgId=${{ secrets.AZURE_MG_TOP }}
            az deployment mg create \
              --name 'Platform-Policy-Definitions' \
              --location ${{ secrets.AZURE_LOCATION }} \
              --management-group-id ${{ secrets.AZURE_MG_TOP }} \
              --template-file ./eslz/policy/customPolicyDiagStgAcct.bicep \
              --parameters location=${{ secrets.AZURE_LOCATION }} \
                           targetMgId=${{ secrets.AZURE_MG_TOP }}